# This is a basic workflow to help you get started with Actions
name: 检测漫画更新
# Controls when the workflow will run
on:
  # watch:
  #   types: started
  workflow_dispatch:
  # repository_dispatch:
  #   types:
  #     - updateManga
  #     #远程触发backupnow
  schedule:
      - cron: '00 22 * * *'
      - cron: '00 3 * * *'
      - cron: '00 9 * * *'
      - cron: '00 14 * * *'
      #快8小时
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      
      - name: install rclone
        run: sudo apt-get install -y rclone

      - name: install python package
        run: pip install requests vthread coloredlogs bottle cryptography

      - name: start api server
        run: nohup python api_server.py &

      - name: deploy aliyun
        env:
          KEY: ${{secrets.KEY}}
        run: |
          wget --post-data '{"key": "'$KEY'"}' http://127.0.0.1:8088/api/getRefreshToken -O /tmp/refreshtoken.bin
          wget  http://127.0.0.1:8088/api/aliyunwebdav/latest/url -O /tmp/aliyundavURL
          wget `cat /tmp/aliyundavURL` -O /tmp/aliyunwebdav.jar
          nohup java -jar /tmp/aliyunwebdav.jar --aliyundrive.refresh-token=`cat /tmp/refreshtoken.bin` --server.port=8900 --aliyundrive.auth.enable=false > /dev/null &
          for ((i=0;i<10;i++))
            do
              echo sleeping $i
              sleep 1
          done


      - name: rclone test
        env: 
          RCLONE_CONFIG_PASS: ${{secrets.RCLONE_CONFIG_PASS}}
        run: 
          rclone --config ./rclone.conf ls 'aliyun:'


      # - name: run main
      #   env:
      #     KEY: ${{secrets.KEY}}
      #     RCLONE_CONFIG_PASS: ${{secrets.RCLONE_CONFIG_PASS}}
      #   run: python main.py
      #   working-directory: ./copymanga

      # - name: report
      #   env:
      #     TOKEN: ${{secrets.MACRODROID_TOKEN}}
      #     TAG: 'important'
      #     TITLE: '漫画更新了'
      #     MSGCHECK: "TRUE"
      #     # TEXT: 'excute over'
      #   run: python report_macrodroid.py
      
      # - name: commit
      #   run: |
      #     git config --global user.email lty6531600@outlook.com
      #     git config --global user.name DriverLin
      #     git pull
      #     git add .
      #     git commit -m "update" -a

      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
